"""Live mode: the real pipeline, emitting the events the page already renders.

The UI was built against `fixture.json`, a recording of a real run. This module produces
the identical event shapes from the actual agents, so the client needed no changes at all —
which is the whole reason the fixture's field names were copied from `schemas.py` rather
than invented.

Two deliberate choices:

* The persona framings are **templated from the typed stage outputs**, not generated by
  another model call. Three extra LLM round trips to rephrase a sentence we already have
  would add latency and a new way to be wrong, on the one screen a judge is guaranteed to
  read. Same facts, three registers, deterministic.
* The write-back proposal comes from the planner's typed `proposed_writes`, so what the
  approval buttons offer is exactly what the executor would receive. A UI that offers a
  different set of actions from the ones the agent proposed would make the gate theatre.
"""
import os
import sys
import time
from pathlib import Path
from typing import AsyncIterator, Dict, List

# Locally `second_unit` lives in ../agent; in the container it is copied next to this file.
# Try the import first and only patch sys.path if it is genuinely missing, so the container
# layout does not depend on a repo-relative path that is not there.
try:
    import second_unit  # noqa: F401
except ImportError:  # pragma: no cover - local dev layout
    AGENT_DIR = Path(__file__).resolve().parent.parent / "agent"
    if AGENT_DIR.is_dir() and str(AGENT_DIR) not in sys.path:
        sys.path.insert(0, str(AGENT_DIR))

from second_unit.pipeline import stream_stage_resilient             # noqa: E402
from second_unit.run import (                                       # noqa: E402
    WATCHTOWER_TASK,
    diagnostician_task,
    next_review_deadline,
)
from second_unit.schemas import (                                   # noqa: E402
    Diagnosis,
    ImpactForecast,
    RemediationPlan,
    WatchtowerReport,
)
from second_unit.stages import (                                    # noqa: E402
    diagnostician,
    impact_forecaster,
    remediation_planner,
    watchtower,
)

STAGE_META = [
    {"id": "watchtower", "label": "Watchtower", "role": "what is on fire"},
    {"id": "diagnostician", "label": "Diagnostician", "role": "why"},
    {"id": "impact_forecaster", "label": "Impact Forecaster", "role": "what it costs"},
    {"id": "remediation_planner", "label": "Remediation Planner", "role": "what to do"},
]


def _hhmm(iso: str) -> str:
    """'2026-08-26T16:09+00:00' -> 'Wed 16:09'. Falls back to the raw string."""
    from datetime import datetime
    try:
        return datetime.fromisoformat(iso).strftime("%a %H:%M")
    except Exception:  # noqa: BLE001
        return iso


def verdict_event(fc: ImpactForecast, dx: Diagnosis) -> dict:
    """The banner. Every number here came out of `forecast_delivery`, not the model."""
    late = not fc.makes_deadline
    slip_txt = f"{abs(fc.slip_hours):.1f}h"
    top_evidence = dx.evidence[0].query if dx.evidence else ""
    ruled_out = [h for h in dx.hypotheses if h.verdict == "ruled_out"]

    return {
        "type": "verdict",
        "severity": "critical" if late else "ok",
        "subject": f"{fc.shot} · {fc.department.upper()} PASS",
        "metrics": [
            {"label": "frames left", "value": f"{fc.frames_remaining:,}"},
            {"label": "throughput", "value": f"{fc.current_rate_per_min:.1f} fr/min",
             "was": f"{fc.baseline_rate_per_min:.1f}"},
            {"label": "ETA", "value": _hhmm(fc.eta_iso), "was": _hhmm(fc.deadline_iso)},
            {"label": "capacity", "value": f"−{fc.capacity_loss_pct:.0f}%"},
        ],
        "personas": {
            # The engineer wants the mechanism and the query behind it.
            "td": {
                "headline": dx.root_cause,
                "sub": (f"{fc.capacity_loss_pct:.0f}% capacity loss on {fc.department}. "
                        f"{len(ruled_out)} suspect(s) ruled out."),
                "action": "Drain the node, then confirm throughput recovers.",
                "detail": top_evidence,
            },
            # The supervisor wants the shot, the size of the problem, and the fix.
            "supervisor": {
                "headline": (f"{fc.shot} {fc.department} is "
                             f"{slip_txt} {'behind' if late else 'ahead of'} the review"),
                "sub": dx.root_cause,
                "action": "One node out of rotation; the rest of the farm is healthy.",
                "detail": f"{fc.frames_remaining:,} frames left at "
                          f"{fc.current_rate_per_min:.1f}/min.",
            },
            # The producer wants the delivery consequence and who is blocked.
            "producer": {
                "headline": fc.verdict,
                "sub": fc.crew_impact,
                "action": "Approve the fix, or move the review.",
                "detail": f"Review {_hhmm(fc.deadline_iso)} · "
                          f"forecast {_hhmm(fc.eta_iso)}.",
            },
        },
    }


def writeback_event(plan: RemediationPlan) -> dict:
    scope_for = {
        "create_annotation": "annotations:write",
        "update_dashboard": "dashboards:write",
        "alerting_manage_rules": "alert.rules:write",
        "create_folder": "folders:write",
    }
    return {
        "type": "writeback_proposed",
        "requires_approval": True,
        "fix_recommendation": plan.fix_recommendation,
        "risk_if_ignored": plan.risk_if_ignored,
        "items": [
            {
                "id": f"item-{i}",
                "kind": w.action,
                "title": w.title,
                "detail": w.details,
                "target": w.rationale,
                "scope": scope_for.get(w.tool, w.tool),
                "reversible": w.reversible,
            }
            for i, w in enumerate(plan.proposed_writes)
        ],
    }


async def iter_live_events() -> AsyncIterator[dict]:
    """Drive the real pipeline, yielding UI events. Never raises: a failed stage is an
    event, because a judge should see where it stopped rather than a dead connection."""
    started = time.time()
    outputs: Dict[str, object] = {}
    total_calls = 0
    stages_ok = 0

    yield {"type": "run_started", "scenario": "live", "stages": STAGE_META}

    # (stage_id, factory, task_fn, schema, fallback_model)
    # Only the two STRONG-model stages get a downgrade path: they are the ones that exhaust
    # quota first, and Flash is a real answer where a 429 is none.
    flash = os.environ.get("GEMINI_MODEL", "gemini-2.5-flash")
    plan: List = [
        ("watchtower", watchtower, lambda: WATCHTOWER_TASK, WatchtowerReport, None),
        ("diagnostician", diagnostician,
         lambda: diagnostician_task(outputs["watchtower"]), Diagnosis, flash),
        ("impact_forecaster", impact_forecaster,
         lambda: (
             "Forecast the production impact of this diagnosis. The client review "
             f"deadline is {next_review_deadline()}. Measure frames remaining and both "
             "the current and pre-incident baseline completion rate, then call "
             f"forecast_delivery.\n\n{outputs['diagnostician'].model_dump_json(indent=2)}"
         ), ImpactForecast, flash),
        ("remediation_planner", remediation_planner,
         lambda: (
             "Propose the fix and the write-back for a human to approve.\n\n"
             f"DIAGNOSIS:\n{outputs['diagnostician'].model_dump_json(indent=2)}\n\n"
             f"IMPACT:\n{outputs['impact_forecaster'].model_dump_json(indent=2)}"
         ), RemediationPlan, None),
    ]

    for stage_id, factory, task_fn, schema, fallback in plan:
        yield {"type": "stage_started", "stage": stage_id}
        result = None
        try:
            async for kind, payload in stream_stage_resilient(
                factory, task_fn(), schema, verbose=False, fallback_model=fallback
            ):
                if kind == "result":
                    result = payload
                elif kind == "tool_done":
                    total_calls += 1
                    yield payload
                elif kind == "retrying":
                    # Surface the wait instead of going silent: dead air on a stream reads
                    # as a hang, and "rate limited, retrying in 8s" reads as a system.
                    yield payload
                # "tool_call" (the pre-response event) is intentionally dropped: emitting
                # both would double every row in the UI. We show the call once it has a
                # real latency to report.
        except Exception as exc:  # noqa: BLE001
            yield {"type": "run_failed", "stage": stage_id,
                   "error": f"{type(exc).__name__}: {exc}",
                   "hint": "The stage raised before returning a result."}
            return

        if result is None or not result.ok:
            err = (result.error if result else "no result")
            quota = any(k in (err or "").lower()
                        for k in ("resource_exhausted", "429", "quota"))
            yield {"type": "run_failed", "stage": stage_id, "error": err,
                   "reason": "quota" if quota else "stage_error",
                   "hint": ("The model is rate limited right now. The recorded "
                            "investigation on this page is a real run and shows the same "
                            "pipeline end to end — press Run investigation without "
                            "?live=1.")
                           if quota else
                           "Later stages were skipped: they depend on this output."}
            return

        outputs[stage_id] = result.output
        stages_ok += 1
        yield {
            "type": "stage_done", "stage": stage_id,
            "seconds": round(result.seconds, 1),
            "tool_calls": len(result.tool_calls),
            "output": result.output.model_dump(mode="json"),
        }

        if stage_id == "impact_forecaster":
            yield verdict_event(outputs["impact_forecaster"], outputs["diagnostician"])
        if stage_id == "remediation_planner":
            yield writeback_event(outputs["remediation_planner"])

    yield {"type": "run_done", "total_tool_calls": total_calls,
           "seconds": round(time.time() - started, 1), "stages_ok": stages_ok}
