"""The dailies briefing: the investigation, spoken, in sixty seconds.

Why this exists rather than a text summary. A VFX crew's morning is a stand-up, not a
dashboard review, the supervisor reads the overnight state aloud while people are still
getting coffee. The whole thesis of Second Unit is that the finding has to arrive in the
form the recipient already uses, and for a producer at 08:00 that form is *someone telling
them*. A page they have to open is one more thing they will not open.

Two design choices worth stating:

* **The script is composed in Python from the typed stage outputs, not generated by another
  model call.** Every number in it has already been computed and verified; asking a model to
  re-narrate them invites a sixth way to be subtly wrong on the one artefact nobody will
  fact-check because it sounds authoritative. Wording is a template; facts are data.
* **It leads with the decision, not the diagnosis.** "SH042 misses Friday by two hours" then
  "here is why" then "here is what to do". A briefing that buries the verdict at the end has
  wasted the only fifteen seconds anyone reliably listens to.

Synthesis is Google Cloud Text-to-Speech (Chirp3-HD), authenticated with ADC.
"""
import base64
import os
import re
from typing import Optional

import google.auth
import google.auth.transport.requests as gr
import requests

#: A British newsreader-ish voice: this is a London/Vancouver studio pipeline, and a calm
#: register suits bad news about a deadline better than an enthusiastic one.
VOICE = os.environ.get("BRIEFING_VOICE", "en-GB-Chirp3-HD-Achernar")
LANGUAGE = os.environ.get("BRIEFING_LANGUAGE", "en-GB")
TTS_URL = "https://texttospeech.googleapis.com/v1/text:synthesize"

_creds = None
_project = None


def _auth() -> tuple:
    """Return (token, quota_project).

    The quota project is not optional: Text-to-Speech rejects Application Default
    Credentials outright, `403 ... requires a quota project`, unless the request carries
    `x-goog-user-project`. Resolving it from three places in order, because relying on the
    environment alone failed silently in the web process, which never loaded .env, and the
    only symptom was a 403 with a long message nobody reads to the end.
    """
    global _creds, _project
    if _creds is None:
        _creds, adc_project = google.auth.default(
            scopes=["https://www.googleapis.com/auth/cloud-platform"])
        _project = (
            os.environ.get("GOOGLE_CLOUD_PROJECT")
            or getattr(_creds, "quota_project_id", None)
            or adc_project
        )
    if not _creds.valid:
        _creds.refresh(gr.Request())
    return _creds.token, _project


def quota_project() -> Optional[str]:
    """Exposed so a caller can report *why* synthesis is unavailable."""
    try:
        return _auth()[1]
    except Exception:  # noqa: BLE001
        return None


def _decap(text: str) -> str:
    """Lowercase a leading capital so a clause can be embedded mid-sentence.

    Naive `text[:4].isupper()` does not work as an acronym guard: "A GP" is all-uppercase
    by that test (the space is ignored), so "A GPU hardware fault..." was left capitalised
    and produced "The cause is A GPU hardware fault". Check the first WORD instead, and
    only protect genuine multi-letter acronyms.
    """
    text = text.strip()
    if not text:
        return text
    first = text.split(" ", 1)[0].strip(",.:;")
    if len(first) > 1 and first.isupper():        # GPU, ECC, SH042, leave alone
        return text
    return text[0].lower() + text[1:]


def _minutes(hours: float) -> str:
    """'1.58' -> 'about an hour and thirty-five minutes'. Spoken, not printed."""
    total = int(round(abs(hours) * 60))
    h, m = divmod(total, 60)
    if h and m:
        return f"about {h} hour{'s' if h > 1 else ''} and {m} minutes"
    if h:
        return f"about {h} hour{'s' if h > 1 else ''}"
    return f"about {m} minutes"


def compose(forecast, diagnosis, plan=None, *, shot: Optional[str] = None) -> str:
    """Build the spoken script from the typed stage outputs."""
    # An explicit subject wins: the console may be asking about a specific pass, and the
    # briefing must name the one the operator selected.
    shot = shot or forecast.shot
    late = not forecast.makes_deadline
    lines = []

    # 1. The decision, first.
    if late:
        lines.append(
            f"Morning. {shot}'s {forecast.department} pass is behind. "
            f"It misses today's client review by {_minutes(forecast.slip_hours)}.")
    else:
        lines.append(
            f"Morning. {shot}'s {forecast.department} pass is running at reduced capacity "
            f"but still makes today's review, with {_minutes(forecast.slip_hours)} to spare.")

    # 2. The number behind it.
    lines.append(
        f"There are {forecast.frames_remaining:,} frames left. The farm is completing "
        f"{forecast.current_rate_per_min:.0f} a minute, down from "
        f"{forecast.baseline_rate_per_min:.0f}, a {forecast.capacity_loss_pct:.0f} percent "
        f"drop in capacity.")

    # 3. Why, in one sentence, with the jargon softened.
    cause = re.sub(r"\s+", " ", diagnosis.root_cause).strip().rstrip(".")
    cause = cause.replace("uncorrectable ECC", "uncorrectable memory")
    # Spoken, so it has to read as a sentence: the root cause arrives capitalised from the
    # model and "The cause: A GPU hardware fault..." sounds like two false starts.
    # State it as its own sentence rather than wrapping it. The model returns root_cause as
    # a complete clause ("A GPU hardware fault on render-07 IS PRODUCING..."), so any
    # "The cause is ..." frame produces a double verb. Keep its own capitalisation.
    lines.append(cause if cause.endswith(".") else cause + ".")

    # 4. What was ruled out: the part that earns trust.
    ruled = [h for h in diagnosis.hypotheses if h.verdict == "ruled_out"]
    if ruled:
        # "including the asset pipeline cache misses are causing the failures" is not a
        # sentence. The hypotheses are full clauses, so they need a frame around them.
        first = _decap(re.sub(r"\s+", " ", ruled[0].statement).strip().rstrip("."))
        if len(ruled) == 1:
            lines.append(f"We also ruled out the possibility that {first}.")
        else:
            lines.append(
                f"We ruled out {len(ruled)} other explanations, including the "
                f"possibility that {first}.")

    # 5. The fix and, if we have it, the counterfactual.
    if plan is not None and getattr(plan, "fix_recommendation", ""):
        fix = re.sub(r"\s+", " ", plan.fix_recommendation).strip().rstrip(".")
        lines.append(f"Recommended: {fix}.")
        if getattr(plan, "fix_makes_deadline", False) and plan.fix_margin_minutes:
            lines.append(
                f"If that happens now, the pass lands {plan.fix_margin_minutes} minutes "
                f"inside the review.")
        elif getattr(plan, "fix_outcome", ""):
            lines.append(plan.fix_outcome.strip())

    # 6. Who is affected.
    if forecast.crew_impact:
        lines.append(re.sub(r"\s+", " ", forecast.crew_impact).strip())

    lines.append("Nothing has been changed in Grafana. The write-back is waiting for "
                 "your approval.")
    return " ".join(lines)


def synthesize(script: str, *, voice: str = None, speaking_rate: float = 1.0) -> bytes:
    """Return MP3 bytes. Raises on failure: the caller decides how to degrade."""
    name = voice or VOICE
    # The language code has to agree with the voice, and the voice name already states it:
    # "en-US-Studio-O" against a hardcoded en-GB is rejected outright. Deriving it from the
    # first two segments means passing any voice just works, instead of working only for the
    # locale that happened to be the default.
    parts = name.split("-")
    language = "-".join(parts[:2]) if len(parts) >= 2 else LANGUAGE
    body = {
        "input": {"text": script},
        "voice": {"languageCode": language, "name": name},
        # Slightly slower than default: this is a number-dense briefing and a producer is
        # half-listening. MP3 so a browser <audio> element can stream it with no plugin.
        "audioConfig": {"audioEncoding": "MP3", "speakingRate": speaking_rate,
                        "sampleRateHertz": 24000},
    }
    token, project = _auth()
    if not project:
        raise RuntimeError(
            "no quota project resolved. Text-to-Speech refuses ADC without "
            "x-goog-user-project. Set GOOGLE_CLOUD_PROJECT.")
    r = requests.post(
        TTS_URL, json=body, timeout=60,
        headers={"Authorization": f"Bearer {token}",
                 "x-goog-user-project": project,
                 "Content-Type": "application/json"},
    )
    if r.status_code >= 400:
        raise RuntimeError(f"text-to-speech {r.status_code}: {r.text[:300]}")
    return base64.b64decode(r.json()["audioContent"])


def estimated_seconds(script: str) -> float:
    """~2.6 words/second at Chirp3-HD's default pace. Used to keep it near 60s."""
    return len(script.split()) / 2.6
